### ISSUE TITLE
Figure out State of Code

### ISSUE THREAD

**Issue by jzf2101** [datamicroscopes/hmm#1]
@dpfau What is the state of the code?

**Comment by dpfau** [comment]
Thrilled you're on this! The state of the code is not-so-great, but mostly in the interface. I got part way through refactoring the code in a more modular, useful form before other obligations took precedent. Eric and I were never able to agree on exactly what counted as "parameter" versus "hyperparameter". For discrete observations this doesn't make a huge difference, but we never decided whether parameters like the scale matrix for an inverse Wishart should be something a user can specify, or something hidden from view and sampled by gridded Gibbs. You can get the most recent version of the code that runs with the old interface by checking out the "last_working" branch.

**Comment by jzf2101** [comment]
:+1: Thanx
